build_wheels:
  image: gitlab-registry.cern.ch/hep-benchmarks/hep-benchmark-suite/hep-benchmark-suite-cc7:qa-v2.1
  stage: build-wheels
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - yum install -y python3-pip sshpass coreutils curl diffutils
    - python3 -m pip install --upgrade pip wheel
    # build all wheels incl. hepscore, release will put into archive
    - pip3 wheel -r requirements.txt --wheel-dir=hepscore_wheels .
    - export PKG_NAME="hepscore-wheels-${CI_COMMIT_TAG}.tar.gz"
    - tar -czvf ${PKG_NAME} hepscore_wheels
    - export PKG_HASH=$(md5sum ${PKG_NAME} | cut -d ' ' -f 1)
    - SSHPASS=${CI_CPUBMK} sshpass -v -e scp -v -oStrictHostKeyChecking=no -r ${PKG_NAME} cpubmk@lxplus.cern.ch:${CI_EOS_RELEASES}
    - curl -o retrieved_file ${CI_WEB_RELEASES}${PKG_NAME}
    - cmp retrieved_file ${PKG_NAME}
    # create release w/ package dl
    # YAML eating special characters :
    - |
      curl -X POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases" \
      --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" \
      --header "Content-Type: application/json" \
      --data "{\"tag_name\": \"${CI_COMMIT_TAG}\", \"name\": \"${CI_COMMIT_TAG}\", \"description\": \"${CI_COMMIT_TAG_MESSAGE:-No release notes.}\", \"assets\": { \"links\": [{ \"name\": \"HEPscore python wheels (md5sum: ${PKG_HASH})\", \"url\": \"${CI_WEB_RELEASES}${PKG_NAME}\", \"link_type\":\"package\" }] }}" \
      --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code:-OK}\n\n"
  artifacts:
    paths:
      - hepscore_wheels
      - hepscore-wheels-$CI_COMMIT_TAG.tar.gz
    when: always
